[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "OrbitRecharge"
description = "Automatically recharge all items on ship when going into orbit."
websiteUrl = "https://github.com/AndreyMrovol/LethalMrovLib/"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
mrov-MrovLib = "0.2.10"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../OrbitRecharge/dist"

[[build.copy]]
source = "../OrbitRecharge/bin/Release/netstandard2.1/OrbitRecharge.dll"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[publish]
communities = [ "lethal-company", ]